name = "simple-a"
license = "MIT"
licenselink = "https://github.com/koebi/simple-a/blob/master/LICENSE.md"
description = "Minimalistic Hugo theme"

tags = []
features = []

[author]
	name = "koebi"
	homepage = "http://ezelo.de/"
	source_repo = "https://github.com/koebi/simple-a"

[original]
	author =  "AlexFinn"
	homepage = "http://ru.alexfinn.eu"
	repo = "http://www.github.com/alexfinn/simple-a"

